config/routes.rb
Tamadamuda::Application.routes.draw do
  devise_for :users, module: :users
  root 'home#landing'
  resources :requests do
    member do
      get :talk
      post :send_message
    end
  end
  resource :client, only: :none do
    get :dashboard
  end
  resource :provider, only: :none do
    get :dashboard
    get :show_profile
    post :update_profile
    post :accept_request
    post :reject_request
  end
end

app/models/interview.rb
class Interview < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/provider_feedback.rb
class ProviderFeedback < ActiveRecord::Base
  belongs_to :provider, class_name: 'User'
  belongs_to :request
end

app/models/provider_profile.rb
class ProviderProfile < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

  state_machine :state, initial: :pending do
    event :accept do
      transition :pending => :accepted
    end

    event :cancel do
      transition :pending => :cancelled
    end
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests
  has_many :provider_feedbacks
  has_one :provider_profile

  def possible_requests
    if provider? && provider_profile.present?
      rejected_requests = ProviderFeedback.where(provider_id: self.id, state: 'rejected').pluck(:request_id) || []

      res = Request.where(service_id: provider_profile.service_id).where(state: :pending)
      if rejected_requests.any?
       res = res.where('id not in (?)', rejected_requests)
      end

      res
    else
      []
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  layout 'application_inner'

  protected

  helper_method :current_provider
  def current_provider
    return current_user if current_user && current_user.provider?
  end

  helper_method :provider_signed_in?
  def provider_signed_in?
    current_provider.present?
  end

  helper_method :current_client
  def current_client
    return current_user if current_user && !current_user.provider?
  end

  helper_method :client_signed_in?
  def client_signed_in?
    current_client.present?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :provider) }
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def dashboard
    @requests = current_client.requests
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application_simple'

  def landing
    if client_signed_in?
      redirect_to dashboard_client_path
    elsif provider_signed_in?
      redirect_to dashboard_provider_path
    end

    @services = Service.all.map{|s| [s.name, s.id]}
    @request = client_signed_in? ? current_client.requests.new : Request.new
  end
end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def dashboard
    @profile = current_provider.provider_profile || current_provider.build_provider_profile

    @requests = current_provider.possible_requests
  end

  def update_profile
    @profile = current_provider.provider_profile || current_provider.build_provider_profile

    @profile.update(profile_params)

    redirect_to dashboard_provider_path
  end

  def reject_request
    @request = Request.find(params[:id])
    ProviderFeedback.create(provider_id: current_provider.id, request: @request, state: 'rejected')
    redirect_to dashboard_provider_path
  end

  def accept_request
    @request = Request.find(params[:id])
    ProviderFeedback.create(provider_id: current_provider.id, request: @request, state: 'accepted')
    redirect_to dashboard_provider_path
  end

  def show_profile
    @profile = current_provider.provider_profile || current_provider.build_provider_profile

  end

  protected

  def profile_params
    params.require(:provider_profile).permit(:name, :phone, :description, :service_id, :urls)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = current_client.requests.new
  end

  def create
    if client_signed_in?
      current_client.requests.create!(requests_params)
      redirect_to dashboard_client_path
    else
      session[:new_request] = requests_params
      redirect_to new_user_registration_path
    end
  end

  def talk
    @request = Request.find(params[:id])
  end

  def send_message
    Danthes.publish_to "/messages/new/#{params[:request_id]}", :chat_message => params[:message], from: "[#{Time.current}] #{params[:from]}"
  end

  protected

  def requests_params
    params.require(:request).permit(:service_id, :max_price, :date)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    layout 'application_simple'

    def create
      super
      if signed_in?(:user) && client_signed_in? && session[:new_request].present?
        current_client.requests.create(session[:new_request])
        session.delete(:new_request)
      end
    end

    protected

    def after_sign_up_path_for(user)
      if user.provider?
        dashboard_provider_path
      else
        dashboard_client_path
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    layout 'application_simple'

    protected

    def after_sign_in_path_for(user)
      if user.provider?
        dashboard_provider_path
      else
        dashboard_client_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/views/clients/dashboard.slim
h1 Личный кабинет

h3.short
  | Заявки
  /i.fa.fa-plus-circle
table.table
  tr
    td Вам нужен
    td Дата
    td Цена
    td
    td
  - @requests.each do |r|
    tr
      td = r.service.name
      /td = r.date
      td 09/05/2014
      td = r.max_price
      td
        - if ProviderFeedback.where(request_id: r.id, state: 'accepted').any?
          = link_to 'Есть отозвавшиеся! Обсудить с исполнителем', talk_request_path(r), class: 'btn btn-primary btn-xs long'
      td = link_to 'Отозвать заявку', '#', class: 'btn btn-warning btn-xs'

= link_to 'Создать новую заявку', new_request_path, class: 'btn btn-success btn-lg grey'
/i.fa.fa-plus-circle

app/views/home/landing.slim
h1
  |Кого вы ищете?
h2.subtitle
  | Бесплатный поиск подрядчиков на любое мероприятие.

.fields_block
  = simple_form_for @request, html: {class: 'form-inline'} do |f|
    .form-group
      = f.input :service_id, collection: @services, include_blank: false, label: 'Мне нужен' ,input_html: {class: 'form-control'}
      = f.input :max_price, label: 'Цена:', input_html: {class: 'form-control'}
      = f.input :date, as: :string, label: 'Дата мероприятия:', input_html: { class: 'datepicker' }
    = f.submit 'Найти', class: 'btn btn-theme'


#carousel-example-generic.carousel.slide data-ride="carousel"
  ol class="carousel-indicators"
    li data-target="#carousel-example-generic" data-slide-to="0" class="active"
    /li data-target="#carousel-example-generic" data-slide-to="1"
    /li data-target="#carousel-example-generic" data-slide-to="2"
    /li data-target="#carousel-example-generic" data-slide-to="3"

  div class="carousel-inner"
    div class="item active"
      .item_wrap
        = image_tag "slide1.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 7 лет
        .profy
          | Отзывов: &nbsp;
          span 167

      .item_wrap
        = image_tag "slide2.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 5 лет
        .profy
          | Отзывов: &nbsp;
          span 98
      .item_wrap
        = image_tag "slide3.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 11 лет
        .profy
          | Отзывов: &nbsp;
          span 270

      .item_wrap
        = image_tag "slide4.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 6 лет
        .profy
          | Отзывов: &nbsp;
          span 175

    div class="item"
      .item_wrap
        = image_tag "slide4.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 7 лет
        .profy
          | Отзывов: &nbsp;
          span 167

      .item_wrap
        = image_tag "slide3.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 5 лет
        .profy
          | Отзывов: &nbsp;
          span 98
      .item_wrap
        = image_tag "slide2.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 11 лет
        .profy
          | Отзывов: &nbsp;
          span 270

      .item_wrap
        = image_tag "slide1.jpg"
        .rating
          | Рейтинг: &nbsp;
          /span.glyphicon.glyphicon-star 5stars
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
          i.fa.fa-star
        .profy
          | Опыт: &nbsp;
          span 6 лет
        .profy
          | Отзывов: &nbsp;
          span 175

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Evenduck</title>

    <%= stylesheet_link_tag    "main/application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body  style="padding-top: 60px;">

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Тамада - мудак. Название - говно', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div id="inner_pages" class="container">
      <%= yield %>

      <hr>

      <footer>
        <p>&copy; Evenduck 2014</p>
      </footer>

    </div>
  </body>
</html>

app/views/layouts/application_inner.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="assets/img/favicon.png">

  <title>Evenduck</title>

  <%= stylesheet_link_tag "main/application", media: "all", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= t('brand') %></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
            <li><%= link_to 'Войти', new_user_session_path %></li>
            <li><%= link_to 'Я хочу предоставлять услуги', new_user_registration_path(provider: true), class: 'big_orange' %></li>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>

<div id="header" class="inner_wrap">

    <div class="light_wrapper">
        <div id="inner_pages" class="container">
            <div class="row">
              <div class="col-lg-12">

                <!--MAIN CONTENT-->
                <%= yield %>

              </div>


              <!-- RIGHT BLOCK-->
              <!--<div class="col-lg-4 col-lg-offset-2">-->


            </div>
        </div>


      <div class="buffer"></div>
    </div>
  <div class="light_wrapper_fixed"></div>


</div>
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <p class="copyright">Copyright &copy; 2014 -
          <%= t('brand') %>
        </p>
      </div>
    </div>
  </div>
</div>

<!--<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>-->
<!--<script src="assets/js/bootstrap.min.js"></script>-->
</body>
</html>

app/views/layouts/application_simple.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">

    <title>Evenduck</title>

    <%= stylesheet_link_tag "main/application", media: "all", "data-turbolinks-track" => true %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="/">
            <%= image_tag 'duck.png', style: "height: 25px; padding-bottom: 3px;" %>
            <%= t('brand') %>
          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
              <li><%= link_to 'Войти', new_user_session_path %></li>
              <li><%= link_to 'Я хочу предоставлять услуги', new_user_registration_path(provider: true), class: 'big_orange' %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

	<div id="header">


      <div id="layout_simple" class="container">
			<div class="row">
				<div class="col-lg-12">

                  <!--MAIN CONTENT-->
                  <%= yield %>

                </div>


              <!-- RIGHT BLOCK-->
              <!--<div class="col-lg-4 col-lg-offset-2">-->


			</div>
		</div>
      <div class="buffer"></div>
	</div>
	<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
					<p class="copyright">Copyright &copy; 2014 -
                    <%= t('brand') %>
                    </p>
			</div>
		</div>
	</div>
	</div>

    <!--<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>-->
    <!--<script src="assets/js/bootstrap.min.js"></script>-->
  </body>
</html>

app/views/providers/_profile.slim
h3 Ваш профиль

br

.form_custom
  = simple_form_for @profile, url: update_profile_provider_path, method: :post do |f|
    = f.input :name, label: 'Ваше имя', input_html: {class: 'form-control'}
    = f.input :phone, label: 'Телефон (будет показан клиенту после его согласия)', input_html: {class: 'form-control'}
    = f.input :service_id, as: :select, collection: Service.all.map{|s| [s.name, s.id]}, include_blank: false, label: 'Какую услугу вы оказываете?', input_html: {class: 'form-control'}
    = f.input :description, as: :text, label: 'Опишите свои услуги', input_html: {class: 'form-control'}
    = f.input :urls, as: :text, label: 'Укажите ссылки на ваши работы через ";"', input_html: {class: 'form-control'}
    = f.submit 'Обновить профиль'

app/views/providers/_requests.slim
h3 Заявки

table.table
  tr
    td Дата
    td Цена
    td Описание
    td
  - @requests.each do |r|
    tr
      /td = r.date
      td 09/05/2014
      td = r.max_price
      td Нужен классный #{r.service.name.mb_chars.downcase}
      td
        = link_to 'Откликнуться', accept_request_provider_path(id: r.id), method: :post, class: 'btn btn-success'
        br
        = link_to 'Не интересно', reject_request_provider_path(id: r.id), method: :post, class: 'btn btn-danger'

        br
        = link_to 'В чат!', talk_request_path(r), class: 'btn'

app/views/providers/dashboard.slim
h2.inline-block Добро пожаловать!
h5.plan-msg Ваш план: тестовый период (осталось 30 дней)
.clearfix

br

ul class="nav nav-tabs" id="myTab"
  li class="active"
    a href="#profile" data-toggle="tab" Профиль
  li
    a href="#offer" data-toggle="tab" Заявки


div class="tab-content"
  div class="tab-pane active" id="profile"
    = render 'profile'
  div class="tab-pane " id="offer"
    = render 'requests'

app/views/providers/show_profile.slim
= @profile.name
br
= @profile.phone
br
= @profile.description
br
/= @profile.service_id
/= binding.pry
- @profile.urls.gsub(/\s+/, '').split(";").each do |p|
 = p
 br

app/views/requests/_form.slim
/.form_custom
/  = simple_form_for @request do |f|
/    .form-group
/      = f.input :service_id, collection: Service.all.map{|s| [s.name, s.id] }, include_blank: false, label: 'Мне нужен' ,input_html: {class: 'form-control'}
/      = f.submit 'Найти'

.fields_block
  = simple_form_for @request, html: {class: 'form-inline'} do |f|
    .form-group
      = f.input :service_id, collection: Service.all.map{|s| [s.name, s.id] }, include_blank: false, label: 'Мне нужен' ,input_html: {class: 'form-control'}
      = f.input :max_price, label: 'Цена:', input_html: {class: 'form-control'}
      = f.input :date, as: :string, label: 'Дата мероприятия:', input_html: { class: 'datepicker' }
    = f.submit 'Найти', class: 'btn btn-theme'

app/views/requests/new.slim
h1 Новая заявка
= render 'form'

app/views/requests/send_message.js.erb
$('#message-text').val('');

app/views/requests/talk.slim
h3 Обсуждение заявки "#{@request.service.name}"

#chat
  #chat-messages.well style="height: 500px; overflow: scroll"

  .form_custom
    #message-form
      = form_tag send_message_request_path, method: :post, remote: true do
        = text_field_tag :message, '', id: 'message-text', input_html: {class: 'form-control'}
        .clearfix
        = hidden_field_tag :request_id, @request.id
        - from = client_signed_in? ? 'Заказчик' : 'Подрядчик'
        = hidden_field_tag :from, from
        = submit_tag 'Отправить'

        - if client_signed_in?
          = link_to 'Показать контакты', '#', id: 'showContacts', class: 'btn', style: 'margin-left: 18px;margin-top: 7px;'

javascript:
  Danthes.debug = true
= subscribe_to "/messages/new/#{@request.id}"
javascript:
  $(function() {
    Danthes.subscribe("/messages/new/#{@request.id}", function(data, channel) {
      $('#chat-messages').append('<span class="message">' + '<b>' + data.from + ':<b/>&nbsp;' + data.chat_message + '</span><br/>');
    });

    $('#showContacts').click(function () {
      $('#showContacts').html('+7 951 23 78 13 (Валера)');
      $('#showContacts').addClass('btn-success');
    });
  });